# Generated by Django 5.0.4 on 2024-05-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
# for this model we created this quary from ORM
# python3 manage.py sqlmigrate app 0001 #this is command
# BEGIN;
# --
# -- Create model JobPost
# --
# CREATE TABLE "app_jobpost" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(200) NOT NULL);
# COMMIT;